# @package callbacks
plot_allencahn_val:
  _target_: bifurcation.callbacks.reconstruction.ReconstructionPlot
  tag: slices
  n_samples: 2
  n_frames: 1
  every_n_epochs: 10
  seed: 0
  split: val
  plotter:
    _target_: bifurcation.viz.allencahn.plot_reconstruction_slices
    _partial_: true
